module.exports = tagsdata = [
  { name: "Motivation", Type: "Positive" },
  { name: "Stress", Type: "Negative" },
  { name: "Anxiety", Type: "Negative" },
  { name: "Deprestion", Type: "Negative" },
  { name: "Happy", Type: "Positive" },
  { name: "Grief", Type: "Negative" },
  { name: "Confidence", Type: "Positive" },
  { name: "Under Confidence", Type: "Negative" },
  { name: "Nervous", Type: "Negative" },
  { name: "Fear", Type: "Negative" },
  { name: "Angry", Type: "Negative" },
  { name: "Success", Type: "Positive" },
  { name: "Failure", Type: "Negative" },
  { name: "Good Life", Type: "Positive" },
  { name: "Bad Mood", Type: "Negative" },
  { name: "Good Vibes", Type: "Positive" },
  { name: "Jealousy", Type: "Negative" },
];
